import React, { useState, useMemo, useEffect, useRef } from "react";
import { toPng } from "html-to-image";
import { calculateUserBMI, bmiCategories } from "../../utils/bmiLogic";

/**
 * @typedef {object} NavProps
 * @property {string} searchTerm - Search term to filter health tips.
 * @property {function} setSearchTerm - Updates the search term state.
 * @property {function} onSearch - Executes the search action.
 * @property {string} [className=''] - Optional additional styling.
 */

const BMIApp = () => {
  // --- REFS & EXPORT LOGIC ---
  const dashboardRef = useRef(null);

  const exportAsImage = async () => {
    const element = dashboardRef.current;
    if (!element) return;

    // 1. Create watermark
    const watermark = document.createElement("div");
    watermark.innerText = "Generated by BMI House - Mustafa";

    watermark.style.position = "absolute";
    watermark.style.bottom = "18px";
    watermark.style.left = "50%";
    watermark.style.transform = "translateX(-50%)";

    watermark.style.fontSize = "12px";
    watermark.style.fontWeight = "700";
    watermark.style.letterSpacing = "0.12em";
    watermark.style.textTransform = "uppercase";

    watermark.style.color = "rgba(100, 116, 139, 0.35)";
    watermark.style.opacity = "0.6";

    watermark.style.pointerEvents = "none";
    watermark.style.zIndex = "9999";

    // 2. Ensure container positioning
    const previousPosition = element.style.position;
    element.style.position = "relative";

    // 3. Append watermark
    element.appendChild(watermark);

    try {
      const dataUrl = await toPng(element, {
        backgroundColor: "#f8fafc",
        pixelRatio: 2,
        cacheBust: true,
      });

      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = `BMI-Report-${new Date().toLocaleDateString()}.png`;
      link.click();
    } catch (err) {
      console.error("Export failed:", err);
      alert("Something went wrong during export.");
    } finally {
      // 4. Cleanup
      element.removeChild(watermark);
      element.style.position = previousPosition;
    }
  };

  // --- STATE INITIALIZATION ---
  const [weight, setWeight] = useState(
    () => Number(localStorage.getItem("bmi-weight")) || 0
  );
  const [height, setHeight] = useState(
    () => Number(localStorage.getItem("bmi-height")) || 0
  );
  const [age, setAge] = useState(
    () => Number(localStorage.getItem("bmi-age")) || 0
  );
  const [unit, setUnit] = useState("metric");

  // --- PERSISTENCE ---
  useEffect(() => {
    localStorage.setItem("bmi-weight", weight);
    localStorage.setItem("bmi-height", height);
    localStorage.setItem("bmi-age", age);
  }, [weight, height, age]);

  // --- CALCULATIONS ---
  const result = useMemo(() => {
    if (!weight || !height) {
      return {
        bmiValue: "0.0",
        matchedCategory: { label: "Waiting...", colorClass: "bg-slate-200" },
      };
    }
    let calc = calculateUserBMI(weight, height, unit);
    if (parseFloat(calc.bmiValue) > 100) calc.bmiValue = "100+";
    return calc;
  }, [weight, height, unit]);

  // --- LOGIC: PERSONALIZED ADVICE ---
  const getPersonalizedTip = () => {
    if (!weight || !height) return "Enter your details to see the magic! ✨";
    const isUnlikely =
      height < 30 || height > 280 || weight < 5 || weight > 500;
    if (isUnlikely) return "🤔 Check your numbers! This seems a bit unusual.";

    const category = result.matchedCategory.label;
    let ageText = "";
    if (age >= 10 && age < 18) ageText = "As a teenager, focus on growth. ";
    else if (age >= 60) ageText = `At ${age}, stay active! `;

    const categoryTips = {
      Normal: "you're doing great! Stay consistent.",
      Overweight: "small habit changes make a big difference.",
      Obese: "prioritize health and daily movement.",
    };

    const tip = Object.keys(categoryTips).find((key) => category.includes(key))
      ? categoryTips[
          Object.keys(categoryTips).find((key) => category.includes(key))
        ]
      : "keep track of your health journey.";

    return ageText + tip;
  };

  const hasData = weight > 0 && height > 0;
  const activeTip = getPersonalizedTip();

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-12 flex flex-col items-center">
      {/* SECTION 1: HEADER & CONTROLS */}
      <div className="w-full max-w-5xl mb-8 flex flex-col sm:flex-row justify-between items-center gap-6 text-center sm:text-left">
        <div>
          <h1 className="text-4xl md:text-5xl font-black text-slate-800 tracking-tighter">
            BMI HOUSE
          </h1>
          <p className="text-slate-400 font-bold text-sm uppercase tracking-widest">
            Health Dashboard
          </p>
        </div>

        <div className="flex items-center gap-4">
          {/* Download Button */}
          <button
            onClick={exportAsImage}
            className="p-3.5 bg-white border border-slate-200 rounded-2xl shadow-sm hover:bg-slate-50 transition-all active:scale-95 group"
            title="Download Report"
          >
            <svg
              className="w-6 h-6 text-slate-600 group-hover:text-emerald-500 transition-colors"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              strokeWidth="2.5"
            >
              <path
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>

          {/* Unit Switcher */}
          <div className="bg-slate-200/50 p-1 rounded-2xl flex relative w-64 h-12 shadow-inner border border-white">
            <div
              className={`absolute top-1 bottom-1 w-[calc(50%-4px)] bg-white rounded-xl shadow-sm transition-all duration-500 ease-out ${
                unit === "metric" ? "left-1" : "left-[calc(50%+2px)]"
              }`}
            ></div>
            <button
              onClick={() => setUnit("metric")}
              className={`relative z-10 flex-1 text-xs font-black transition-all ${
                unit === "metric" ? "text-emerald-600" : "text-slate-400"
              }`}
            >
              METRIC
            </button>
            <button
              onClick={() => setUnit("imperial")}
              className={`relative z-10 flex-1 text-xs font-black transition-all ${
                unit === "imperial" ? "text-emerald-600" : "text-slate-400"
              }`}
            >
              IMPERIAL
            </button>
          </div>
        </div>
      </div>

      {/* SECTION 2: MAIN DASHBOARD (Export Container) */}
      <div
        ref={dashboardRef}
        id="bmi-export-container"
        className="w-full max-w-5xl p-2"
      >
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 w-full">
          {/* LEFT: GAUGE & INPUTS */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            <div className="bg-white rounded-[2.5rem] shadow-2xl shadow-slate-200/50 p-8 md:p-10 border border-white flex flex-col items-center">
              {/* BMI Gauge */}
              <div className="relative w-44 h-44 md:w-56 md:h-56 flex items-center justify-center rounded-full border-12 border-slate-50 shadow-inner mb-10">
                <div className="text-center">
                  <span className="text-4xl md:text-6xl font-black text-neutral-700">
                    {result.bmiValue}
                  </span>
                  <p className="text-xs font-bold text-slate-300 uppercase tracking-widest mt-1">
                    BMI Score
                  </p>
                </div>
                <div
                  className={`absolute inset-0 rounded-full border-12 border-transparent border-t-current border-r-current -rotate-45 transition-all duration-1000 ${
                    hasData
                      ? result.matchedCategory.colorClass.replace(
                          "bg-",
                          "text-"
                        )
                      : "text-slate-200"
                  }`}
                ></div>
              </div>

              {/* Inputs Group */}
              <div className="w-full grid grid-cols-3 gap-4 mb-10">
                {[
                  {
                    label: unit === "metric" ? "Weight (kg)" : "Weight (lb)",
                    val: weight,
                    set: setWeight,
                  },
                  {
                    label: unit === "metric" ? "Height (cm)" : "Height (in)",
                    val: height,
                    set: setHeight,
                  },
                  { label: "Age", val: age, set: setAge },
                ].map((input) => (
                  <div key={input.label} className="flex flex-col gap-2">
                    <label className="text-[10px] font-black text-slate-400 uppercase text-center tracking-wider">
                      {input.label}
                    </label>
                    <input
                      type="number"
                      value={input.val || ""}
                      onChange={(e) => input.set(Number(e.target.value))}
                      className="bg-slate-50 p-4 md:p-5 rounded-2xl text-center font-black text-neutral-700 text-lg md:text-xl focus:border-emerald-400! focus:bg-white transition-all border border-transparent outline-none shadow-sm"
                      placeholder="0"
                    />
                  </div>
                ))}
              </div>

              {/* Advice Card */}
              <div className="w-full bg-slate-50/80 rounded-[2.5rem] p-6 border border-slate-100 relative overflow-hidden">
                <p className="relative z-10 text-sm md:text-base text-neutral-700 font-bold leading-relaxed">
                  {activeTip}
                </p>
                <div
                  className={`absolute -right-4 -bottom-4 w-20 h-20 rounded-full blur-2xl opacity-20 ${result.matchedCategory.colorClass}`}
                ></div>
              </div>
            </div>
          </div>

          {/* RIGHT: MATRIX */}
          <div className="lg:col-span-7 bg-white rounded-[2.5rem] shadow-2xl shadow-slate-200/50 p-8 md:p-10 border border-white">
            <h3 className="text-xl md:text-2xl font-black text-neutral-700 mb-8 tracking-wide">
              Classification Matrix
            </h3>
            <div className="flex flex-col gap-3 md:gap-4">
              {bmiCategories.map((cat) => {
                const isActive =
                  hasData && result.matchedCategory.label === cat.label;
                return (
                  <div
                    key={cat.label}
                    className={`flex items-center justify-between p-4 md:p-5 rounded-2xl transition-all duration-500 ${
                      isActive
                        ? "bg-slate-50 shadow-inner border border-emerald-100 ring-1 ring-emerald-50 scale-[1.02]"
                        : "opacity-40"
                    }`}
                  >
                    <div className="flex items-center gap-5">
                      <div
                        className={`w-4 h-4 rounded-full ${cat.colorClass} ${
                          isActive
                            ? "animate-bounce [animation-iteration-count:3] ring-4 ring-white shadow-lg"
                            : ""
                        }`}
                      ></div>
                      <div className="flex flex-col">
                        <span
                          className={`text-sm md:text-base ${
                            isActive
                              ? "font-black text-neutral-700"
                              : "font-bold text-slate-500"
                          }`}
                        >
                          {cat.label}
                        </span>
                        {isActive && (
                          <span className="text-[9px] text-emerald-500 font-black uppercase tracking-wide">
                            Current Status
                          </span>
                        )}
                      </div>
                    </div>
                    <span
                      className={`text-sm md:text-base font-black ${
                        isActive ? "text-neutral-600" : "text-slate-400"
                      }`}
                    >
                      {cat.rangeText}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BMIApp;
